version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todolist
    restart: always
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todolist-network

  todolist-api:
    build: .
    container_name: todolist-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todolist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - todolist-network

volumes:
  db_data:


networks:
  todolist-network:
    driver: bridge