spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todolist
    username: root
    password: 458126
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
